dist: trusty
sudo: false
language: python
python:
  - "3.5"
notifications:
  email: false
#
# commands to install dependencies and the script itself
addons:
  apt:
    sources:
    - sourceline: "deb http://build.openmodelica.org/apt `lsb_release -cs` nightly"
      key_url: "http://build.openmodelica.org/apt/openmodelica.asc"
    packages:
    - omc
    - omlib-modelica-3.2.2
    - tidy
install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy numpy
  - pip install git+git://github.com/OpenModelica/OMPython.git
  - pip install pytidylib
#
# commands to run the tests
script: 
  - python --version
  - omc --version
  - python test_Script.py
